---
name: build

on:
  workflow_dispatch:

  workflow_call:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  target_ref: ${{ github.head_ref || github.ref_name }}
  GO111MODULE: on
  GOPRIVATE: ''

jobs:
  build:
    name: Build, Test and Check code

    strategy:
      matrix:
        go-version: [1.21.x]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: actions/checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac #v4.0.0
        with:
          repository: ${{ github.repository }}
          ref: ${{ env.target_ref }}
          token: ${{ github.token }}
          # Full git history is needed to get a proper list of changed files
          # within `super-linter`.
          fetch-depth: 0

      - name: actions/setup-go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: ${{ matrix.go-version }}

      - name: go version
        run: go version

      - name: go mod tidy
        run: go mod tidy

      - name: go clean --cache
        run: go clean --cache

      - name: go build (verbose)
        run: |
          go env
          go build -v ./...
