---
name: Linter - Run full battery of linters

on:
  workflow_dispatch:

  workflow_call:

  push:

  pull_request:

env:
  target_ref: ${{ github.head_ref || github.ref_name }}
  GO111MODULE: on
  GOPRIVATE: ''

jobs:
  linter:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: actions/checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac #v4.0.0
        with:
          repository: ${{ github.repository }}
          ref: ${{ env.target_ref }}
          token: ${{ github.token }}
          # Full git history is needed to get a proper list of changed files
          # within `super-linter`.
          fetch-depth: 0

      - name: super-linter/super-linter
        uses: super-linter/super-linter@v5
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ github.token }}
          LOG_LEVEL: VERBOSE
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_EDITORCONFIG: false
          VALIDATE_GITHUB_ACTIONS: false
